### ISSUE TITLE
manual install flvtool2 on ubuntu 16.04

### ISSUE THREAD

**Issue by meisaputra** [unnu/flvtool2#9]
i need manual install flvtool2 because install by apt is not available anymore for flvtool2.
then i install ruby before compile flvtool2. succeed. i got ruby version 2.3.1p112.

when i run:
$ruby setup.rb config

i got these message:
=====
setup.rb:283: warning: key "bin-dir" is duplicated and overwritten on line 284
setup.rb:788:in `load_rbconfig': uninitialized constant Config (NameError)
Did you mean?  RbConfig
	from setup.rb:768:in `invoke'
	from setup.rb:1578:in `<main>'
=====
how to compile flvtool correctly?

**Comment by DeeJaVu** [comment]
Bro are u fucking kidding me ??????? 

just install using `gem install flvtool2`
